basic.show_icon(IconNames.HAPPY)
basic.pause(1000)
basic.clear_screen()
scrollbit.set_all(0)
scrollbit.show()
basic.pause(1000)
scrollbit.clear()

def on_forever():
    basic.show_number(1)
    scrollbit.set_arrow(ArrowNames.NORTH, 0, 0, 128)
    scrollbit.show()
    basic.pause(1000)
    basic.clear_screen()
    scrollbit.clear()
    basic.show_number(2)
    scrollbit.scroll_text("TONDA", 128, 50)
    basic.pause(1000)
    basic.clear_screen()
    scrollbit.clear()
basic.forever(on_forever)
